import { Heading, HStack, SimpleGrid, Stack, Box, Spinner } from "@chakra-ui/react";
import { useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import { getProducts } from "../redux/products/creators";
import ProductCard from "../components/ProductCard";
import Filter from "../components/Filter";

export default function Products(params) {
	const products = useSelector((state) => state.productsState.products);
	// const products = getDummyProducts();
	const dispatch = useDispatch();

	useEffect(() => {
		if (!products) {
			dispatch(getProducts({}));
		}
	}, []);

	if (!products) {
		return (
			<Spinner
				padding="30px"
				margin="200px"
				thickness="7px"
				speed="0.3s"
				emptyColor="gray"
				color="blue"
				size="xl"
			/>
		);
	}

	return (
		<Stack flexDirection="row" padding="10px" gap="10px" alignItems="stretch">
			<Box flex="1" marginTop="15px">
				<Filter />
			</Box>
			<SimpleGrid
				columns={{ base: 1, md: 2, lg: 3 }}
				spacing="20px"
				padding="10px"
				flex="3"
				margin="auto"
			>
				{products.map((product) => (
					<ProductCard product={product} />
				))}
			</SimpleGrid>
		</Stack>
	);
}

function getDummyProducts() {
	return [
		{
			_id: 2,
			name: "iWatch 9",
			category: "Watch",
			image: "https://drive.google.com/file/d/1Ssupy_0WqRGOnip5JPcr7knn-0prCfn5/view?usp=sharing",
			color: "Yellow",
			phoneSize: 4.7,
			watchSize: 42,
			strapMaterial: "Fabric",
			shape: "Round",
			body: "Glass",
			waterResistant: false,
			camera: 12,
			battery: 11,
			touchSensor: false,
			faceLock: true,
			display: "Liquid Ratina",
			storage: 16,
			phoneWeight: 200,
			watchWeight: 35,
			airpodWeight: 7,
			connectivity: 3,
			generation: 3,
			rating: 1.5,
			bandSize: "Medium",
			price: 25000,
		},
		{
			_id: 3,
			name: "AirPods",
			category: "Airpod",
			image: "https://drive.google.com/file/d/1Jd7A_HSGrpKmW4pIr2CNnZvvU4BzjoJu/view?usp=sharing",
			color: "Blue",
			phoneSize: 5.2,
			watchSize: 46,
			strapMaterial: "Fabric",
			shape: "Rectangular",
			body: "Glass",
			waterResistant: true,
			camera: 7,
			battery: 16,
			touchSensor: false,
			faceLock: false,
			display: "Super Ratina",
			storage: 128,
			phoneWeight: 250,
			watchWeight: 35,
			airpodWeight: 4,
			connectivity: 3,
			generation: 2,
			rating: 3.9,
			bandSize: "Large",
			price: 15000,
		},
		{
			_id: 4,
			name: "AirPods Pro",
			category: "Airpod",
			image: "https://drive.google.com/file/d/1UZhy0nIaCDTnAb2V-KBtySTsk2tzbA0E/view?usp=sharing",
			color: "Green",
			phoneSize: 6.5,
			watchSize: 46,
			strapMaterial: "Elastomer",
			shape: "Rectangular",
			body: "Steel",
			waterResistant: true,
			camera: 5,
			battery: 12,
			touchSensor: true,
			faceLock: true,
			display: "Super Ratina",
			storage: 32,
			phoneWeight: 220,
			watchWeight: 25,
			airpodWeight: 4,
			connectivity: 4,
			generation: 2,
			rating: 2.6,
			bandSize: "Large",
			price: 15000,
		},
		{
			_id: 5,
			name: "iPhone 10",
			category: "Phone",
			image: "https://drive.google.com/file/d/1aBkKaIY9A52Wa7oOk4sREA2XDADnr6hz/view?usp=sharing",
			color: "Silver",
			phoneSize: 5.2,
			watchSize: 50,
			strapMaterial: "Silicon",
			shape: "Round",
			body: "Glass",
			waterResistant: true,
			camera: 12,
			battery: 12,
			touchSensor: false,
			faceLock: true,
			display: "Liquid Ratina",
			storage: 64,
			phoneWeight: 200,
			watchWeight: 35,
			airpodWeight: 6,
			connectivity: 3,
			generation: 3,
			rating: 3.8,
			bandSize: "Small",
			price: 30000,
		},
		{
			_id: 6,
			name: "AirPods Max",
			category: "Airpod",
			image: "https://drive.google.com/file/d/1Jd7A_HSGrpKmW4pIr2CNnZvvU4BzjoJu/view?usp=sharing",
			color: "Blue",
			phoneSize: 4.7,
			watchSize: 46,
			strapMaterial: "Fabric",
			shape: "Round",
			body: "Aluminium",
			waterResistant: false,
			camera: 12,
			battery: 16,
			touchSensor: true,
			faceLock: true,
			display: "Super Ratina",
			storage: 32,
			phoneWeight: 150,
			watchWeight: 30,
			airpodWeight: 6,
			connectivity: 4,
			generation: 2,
			rating: 1.9,
			bandSize: "Large",
			price: 55000,
		},
		{
			_id: 7,
			name: "iWatch 6 SE",
			category: "Watch",
			image: "https://drive.google.com/file/d/1We0KQwQDKKI32MDGRc-pBI37pyEzxYDo/view?usp=sharing",
			color: "Pink",
			phoneSize: 4.7,
			watchSize: 48,
			strapMaterial: "Silicon",
			shape: "Rectangular",
			body: "Steel",
			waterResistant: false,
			camera: 5,
			battery: 12,
			touchSensor: true,
			faceLock: false,
			display: "Ratina",
			storage: 512,
			phoneWeight: 170,
			watchWeight: 30,
			airpodWeight: 4,
			connectivity: 3,
			generation: 4,
			rating: 4.2,
			bandSize: "Large",
			price: 45000,
		},
		{
			_id: 8,
			name: "iWatch 8",
			category: "Watch",
			image: "https://drive.google.com/file/d/1-vKZ-SE-1G0iVelAmlyCPnObkV3JHstp/view?usp=sharing",
			color: "Red",
			phoneSize: 4.5,
			watchSize: 46,
			strapMaterial: "Elastomer",
			shape: "Square",
			body: "Steel",
			waterResistant: true,
			camera: 5,
			battery: 13,
			touchSensor: true,
			faceLock: true,
			display: "Super Ratina",
			storage: 32,
			phoneWeight: 220,
			watchWeight: 30,
			airpodWeight: 7,
			connectivity: 5,
			generation: 4,
			rating: 3.8,
			bandSize: "Medium",
			price: 85000,
		},
		{
			_id: 9,
			name: "iPhone 7 Max",
			category: "Phone",
			image: "https://drive.google.com/file/d/1dPQ7d27dFkZBoWwei58W25lqq2eCSo4Z/view?usp=sharing",
			color: "Blue",
			phoneSize: 4.7,
			watchSize: 44,
			strapMaterial: "Fabric",
			shape: "Square",
			body: "Glass",
			waterResistant: false,
			camera: 7,
			battery: 12,
			touchSensor: false,
			faceLock: false,
			display: "Liquid Ratina",
			storage: 32,
			phoneWeight: 170,
			watchWeight: 35,
			airpodWeight: 7,
			connectivity: 3,
			generation: 3,
			rating: 2.9,
			bandSize: "Small",
			price: 30000,
		},
		{
			_id: 10,
			name: "iWatch 8 Ultra",
			category: "Watch",
			image: "https://drive.google.com/file/d/1g21Sh8eb8fISZYSIU7t8rZCtDCMqCPQa/view?usp=sharing",
			color: "Gold",
			phoneSize: 4.5,
			watchSize: 40,
			strapMaterial: "Fabric",
			shape: "Round",
			body: "Glass",
			waterResistant: false,
			camera: 7,
			battery: 16,
			touchSensor: false,
			faceLock: false,
			display: "Ratina",
			storage: 128,
			phoneWeight: 170,
			watchWeight: 25,
			airpodWeight: 3,
			connectivity: 3,
			generation: 2,
			rating: 2.7,
			bandSize: "Large",
			price: 45000,
		},
		{
			_id: 11,
			name: "iPhone 8 SE 1-Gen",
			category: "Phone",
			image: "https://drive.google.com/file/d/12H7kooAglx1Ki3T2pvAI3cRFVxFsX1Ea/view?usp=sharing",
			color: "Purple",
			phoneSize: 5.5,
			watchSize: 42,
			strapMaterial: "Fabric",
			shape: "Round",
			body: "Aluminium",
			waterResistant: false,
			camera: 7,
			battery: 16,
			touchSensor: true,
			faceLock: false,
			display: "Liquid Ratina",
			storage: 16,
			phoneWeight: 200,
			watchWeight: 50,
			airpodWeight: 4,
			connectivity: 5,
			generation: 2,
			rating: 1.9,
			bandSize: "Medium",
			price: 20000,
		},
		{
			_id: 12,
			name: "AirPods Max Pro",
			category: "Airpod",
			image: "https://drive.google.com/file/d/1crTJqUhGAZGla8GWlkzUO5WwRC5OF034/view?usp=sharing",
			color: "Red",
			phoneSize: 4.5,
			watchSize: 40,
			strapMaterial: "Fabric",
			shape: "Round",
			body: "Glass",
			waterResistant: true,
			camera: 12,
			battery: 11,
			touchSensor: true,
			faceLock: true,
			display: "Super Ratina",
			storage: 16,
			phoneWeight: 150,
			watchWeight: 30,
			airpodWeight: 3,
			connectivity: 4,
			generation: 3,
			rating: 3.7,
			bandSize: "Large",
			price: 80000,
		},
	];
}
